# Generated by Django 5.0.3 on 2024-03-11 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='Название категории товаров', max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('place_id', models.CharField(help_text='Уникальный идентификатор места покупки', max_length=50, verbose_name='Place ID')),
                ('place_name', models.CharField(help_text='Название места покупки', max_length=150, verbose_name='Place Name')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ('place_name',),
            },
        ),
        migrations.CreateModel(
            name='CategoryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Общая сумма потраченная на категорию за промежуток времени', max_digits=10, verbose_name='Total Spent')),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0.0, help_text='Средний чек по категории', max_digits=10, verbose_name='Average Receipt')),
                ('category', models.ForeignKey(help_text='Категория товара', on_delete=django.db.models.deletion.CASCADE, to='consumer.category')),
            ],
            options={
                'verbose_name': 'Category Analytics',
                'verbose_name_plural': 'Category Analytics',
                'unique_together': {('category',)},
            },
        ),
        migrations.CreateModel(
            name='PurchaseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total_purchases', models.PositiveIntegerField(default=0, help_text='Общее количество покупок в данном месте', verbose_name='Total Purchases')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Общая стоимость покупок', max_digits=10, verbose_name='Total Amount')),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0.0, help_text='Средний чек в данном месте', max_digits=10, verbose_name='Average Receipt')),
                ('total_nds', models.DecimalField(decimal_places=2, default=0.0, help_text='Общая сумма НДС за промежуток времени', max_digits=10, verbose_name='Total NDS')),
                ('total_tips', models.DecimalField(decimal_places=2, default=0.0, help_text='Общая сумма чаевых за промежуток времени', max_digits=10, verbose_name='Total Tips')),
                ('category_analytics', models.ManyToManyField(related_name='category_analytics', to='consumer.categoryanalytics')),
                ('place', models.ForeignKey(blank=True, help_text='Место покупки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumer.place')),
            ],
            options={
                'verbose_name': 'Purchase analytics',
                'verbose_name_plural': 'Purchases analytics',
            },
        ),
        migrations.CreateModel(
            name='OverallAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('purchase_analytics', models.ManyToManyField(related_name='purchase_analytics', to='consumer.purchaseanalytics')),
            ],
            options={
                'verbose_name': 'Overall Analytics',
                'verbose_name_plural': 'Overall Analytics',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена в категории', max_digits=10, verbose_name='Price')),
                ('name', models.ForeignKey(help_text='Название категории', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='consumer.category')),
            ],
            options={
                'verbose_name': 'Purchase in category',
                'verbose_name_plural': 'Purchases in category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена покупки', max_digits=10, verbose_name='Price')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма НДС в чеке', max_digits=10, verbose_name='NDS')),
                ('tips', models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма чаевых в чеке', max_digits=10, verbose_name='Tips')),
                ('place', models.ForeignKey(help_text='Место покупки', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='consumer.place')),
                ('purchase_in_category', models.ManyToManyField(related_name='purchases_in_category', to='consumer.purchaseincategory')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ('-id',),
            },
        ),
    ]
